version: 1.0.{build}
image: Visual Studio 2019
configuration:
    - Release
nuget:
  account_feed: true
  project_feed: true

artifacts:
- path: .\src\Iridium.Callee\bin\Release\publish\
  name: Iridium
  type: WebDeployPackage
deploy:
- provider: GitHub
  auth_token:
    secure: WAfIsXkzH0DOMQ3//IB7Xp4PC8YCAr0TME4cqwcpodyNI2j+Fmg7La6Q9Wiw92oQ
  artifact: /.*\.zip/